### ISSUE TITLE
Add Instagram to Social>Sharing Networks to be put in footer

### ISSUE THREAD

**Issue by rstetz** [CherryFramework/cherry-social#2]
www.gristhouse.com

is it possible to add instagram icon at the bottom with Facebook and twitter? I'm a newb at this so...

**Comment by cheh** [comment]
Yes, of course. 

Dashboard - Cherry - Social - Follow Us networks:
![screenshot_1](https://cloud.githubusercontent.com/assets/2461627/12594736/2f770aaa-c480-11e5-8e05-4df81d6c7c61.png)

**Comment by rstetz** [comment]
Thanks!
